version: "3.8"

services:
    mysql:
        image: mysql:5.7
        ports:
            - 12345:3306
        command: [
            "--default_authentication_plugin=mysql_native_password",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci"
        ]
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wp
            MYSQL_PASSWORD: 123
        volumes:
            - ./var/dump:/docker-entrypoint-initdb.d
            - ./var/conf:/etc/mysql/conf.d
            - ./var/mysql:/var/lib/mysql
        networks:
            - default

    wordpress:
        build:
            context: ./docker
            dockerfile: Dockerfile-wordpress
        depends_on:
            - mysql
        ports:
            - 8081:80
        links:
            - mysql:db
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: 123
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_CONFIG_EXTRA: |
                define("FS_METHOD", "direct");
                define("WP_DEBUG", true);
        volumes:
            - ./var/plugins:/var/www/html/wp-content/plugins
            - ./var/uploads:/var/www/html/wp-content/uploads
            - ./src/NorthernBeatPlugin:/var/www/html/wp-content/plugins/NorthernBeatPlugin
            - ./src/NorthernBeatTheme:/var/www/html/wp-content/themes/NorthernBeatTheme
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        links:
            - mysql:db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: wp
            MYSQL_PASSWORD: 123
